[package]
name = "nightcycle/package"
description = "A package!"
version = "0.1.0"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
Maid = "nightcycle/maid@2.2.2"
ServiceProxy = "nightcycle/service-proxy@1.0.5"
Queue = "nightcycle/queue@2.3.3"
Signal = "sleitnick/signal@2.0.3"
